[project]
name = "exif-lambda"
version = "0.1.0"
description = "Lambda function to extract EXIF data from images"
requires-python = ">=3.13"
dependencies = [
    # Add your dependencies here
    # Example: "pillow>=10.0.0"
]
